#!/usr/bin/env node

var route = require('./routes');
var static = require('../utils/static');

function get(req, res, ops){
    
    if(req.url === '/'){

        route.home(req, res);

    }
    
    else
    if ( req.url === '/css/home.css'){

        static.script(res, './view/css/home.css');

    }
    
    else {

        res.end();
        
    }
    
}

module.exports = get;
